# Function to be run that computes observations and climate sensitivities

import UKESMlib
import pandas as pd
import typing
type_basic = int|float|str|bool
def comp_obs_feedback(run_submit_instance,
                      parameter_dict:dict[str,dict[str,type_basic]]) -> typing.Optional[pd.Series]:
    """
    Function to compute obs and feedbacks for a given run/submit instance and parameter dictionary.
    Is example of a function that can be used to run multiple models. No need to raise errors on None.
    that gets handled by the calling code.
    This function  computes simulated  observations and Cess feeback.
      Assumes using names generated by comp_sim_obs_UKESM1_1_1 and needs two models:
       'control' and '+4K' -- AMIP run & AMIP run with +4K SST
       and two obs:
        'netflux_global' and 'T_global'. global mean net TOA flux and global mean surface temperature.
    :param run_submit_instance: a runSubmit instance
    :param parameter_dict: dictionary of parameters to set for the model.
    :return: a pandas series with the observations and feedbacks.
    """

    my_logger = UKESMlib.my_logger
    models = dict()
    obs = dict()
    # get models and simulated obs. This case has no dependencies between models so is straightforward.
    # a more complex case would be where one model depends on another.
    # in that case would need to run models in expected order checking that they exist before running dependent models.
    # more complex cases could be handled by modifying parameters in models based on results from other models.
    for name,param_dict in parameter_dict.items():
        models[name] = run_submit_instance.make_model(param_dict) # this will create a new model or return an existing one.
        obs[name]:typing.Optional[pd.Series] = models[name].simulated_obs # get the simulated obs for this model. If None model not been run yet.
    # test that all models ran and produced obs. Any that are None will mean can't compute result.
    if any([o is None for o in obs.values()]):
        return None
    # now we can compute the feedbacks
    d_flux = obs['+4K'].loc['netflux_global'] - obs['control'].loc['netflux_global']
    d_temp =  obs['+4K'].loc['T_global'] - obs['control'].loc['T_global'] # should be close to 4K. Slightly different as land may warm more than ocean.
    cess = -d_flux/d_temp # Cess feedback in W/m2/K
    my_logger.debug(f'Computed CESS = {cess} W/m2/K for dFlux={d_flux} W/m2 and dtemp={d_temp} K')
    result = obs['control'].append(pd.Series({'Cess':cess}))
    return result

